services:
  db:
    image: postgres:14.5
    restart: always
    ports:
      - '3555:5432'
    environment:
      USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
