services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    image: bapp/api
    command: yarn start:dev
    ports:
      - '3000:3000'
    container_name: bapp-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - DB_PORT=5432
      - DB_HOST=db
    volumes:
      - ./src/:/app/src
     
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    ports:
      - '3555:5432'
    user: postgres
    container_name: bapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bapp
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 30s
    volumes:
      - bappdb-pgdata:/var/lib/postgressql/data


volumes:
  bappdb-pgdata:

