export enum Category {
  Utilities = 'Utilities',
  Insurance = 'Insurance',
  Housing = 'Housing',
  HealthCare = 'Health Care',
  Debt = 'Debt',
  Clothing = 'Clothing',
  PersonalCare = 'Personal Care',
  PropertyTaxes = 'Property Taxes',
  BlackTax = 'Black Tax',
  Entertainment = 'Entertainment',
  Retirement = 'Retirement Saving',
  Food = 'Food',
  Restaurant = 'Restaurant',
  Travel = 'Travel',
  Sport = 'Sport',
  Gym = 'Gym',
  MaintenanceRepairs = 'Maintenance and Repairs',
  Transport = 'Transport',
  Childcare = 'Child Care',
  Investment = 'Investment',
  Saving = 'Saving',
  Miscellaneous = 'Miscellaneous',
}
